import assert from "node:assert/strict";
import test from "node:test";
import {
  mkdtemp,
  mkdir,
  writeFile,
  readFile,
  rm,
  symlink,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { zipSync } from "fflate";
import { buildContext } from "../src/context";
import { parseProjectPath } from "../src/project";
import {
  findGeneratedIosProject,
  parseYy,
  prepareIosFrameworks,
  preflightIos,
  safeArchivePath,
  runnerHashes,
  verifyStagedIosRunner,
} from "../src/gms2/ios";
import { gms2Schema } from "../src/gm-options";
import { constructIgorBuildArgs } from "../src/gms2/use-gms2";
const ctx = buildContext(process);
async function temporary(t: { after: (fn: () => Promise<void>) => void }) {
  const root = await mkdtemp(path.join(tmpdir(), "gm-ios-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  return root;
}
async function file(p: string, data: string | Uint8Array = "") {
  await mkdir(path.dirname(p), { recursive: true });
  await writeFile(p, data);
}
test("reject missing generation even when another invocation has an old project", async (t) => {
  const root = await temporary(t);
  await file(path.join(root, "old/Game.xcodeproj/project.pbxproj"));
  await mkdir(path.join(root, "fresh"));
  await assert.rejects(
    findGeneratedIosProject(ctx, path.join(root, "fresh")),
    /found 0/,
  );
});
test("accept one generated project and ignore Pods; reject ambiguous outputs", async (t) => {
  const root = await temporary(t);
  const project = path.join(root, "output/Game.xcodeproj");
  await file(path.join(project, "project.pbxproj"));
  await file(path.join(root, "output/Pods/Pods.xcodeproj/project.pbxproj"));
  assert.equal(await findGeneratedIosProject(ctx, root), project);
  await file(path.join(root, "output/Other.xcodeproj/project.pbxproj"));
  await assert.rejects(findGeneratedIosProject(ctx, root), /found 2/);
});
test("project discovery never follows symlinks outside the invocation", async (t) => {
  const root = await temporary(t);
  await file(path.join(root, "outside/Game.xcodeproj/project.pbxproj"));
  await mkdir(path.join(root, "fresh"));
  await symlink(path.join(root, "outside"), path.join(root, "fresh/link"));
  await assert.rejects(
    findGeneratedIosProject(ctx, path.join(root, "fresh")),
    /found 0/,
  );
});
test("GameMaker trailing commas do not change strings", () => {
  assert.deepEqual(
    parseYy('{"text": "literal ,} and \\"quoted\\"", "items":[1,],}'),
    { text: 'literal ,} and "quoted"', items: [1] },
  );
});
test("reject unsafe framework archive destinations", () => {
  for (const name of [
    "/absolute",
    "../escape",
    "Fw/../../escape",
    "a//b",
    "a/./b",
    "a\\b",
    "C:/escape",
    "\0x",
  ]) {
    assert.equal(safeArchivePath(name), false, name);
  }
  assert.equal(safeArchivePath("Name.xcframework/ios-arm64/Name"), true);
});
async function frameworkFixture(
  t: { after: (fn: () => Promise<void>) => void },
  entries: Record<string, Uint8Array>,
) {
  const root = await temporary(t);
  const project = parseProjectPath(ctx, path.join(root, "source/Game.yyp"));
  await file(
    project,
    '{"resources":[{"id":{"path":"extensions/Test/Test.yy"}},],}',
  );
  const zip = path.join(
    root,
    "source/extensions/Test/iOSSourceFromMac/Test.zip",
  );
  await file(zip, zipSync(entries));
  const generated = path.join(root, "generated");
  await mkdir(generated);
  return { root, project, generated, zip };
}
test("prepare referenced framework ZIPs and allow identical contents already generated by Igor", async (t) => {
  const bytes = Buffer.from("framework");
  const f = await frameworkFixture(t, { "Test.xcframework/Info.plist": bytes });
  await prepareIosFrameworks(ctx, f.project, f.generated);
  await prepareIosFrameworks(ctx, f.project, f.generated);
  assert.deepEqual(
    await readFile(path.join(f.generated, "Fw/Test.xcframework/Info.plist")),
    bytes,
  );
  await file(
    path.join(f.generated, "Fw/Test.xcframework/Info.plist"),
    "different",
  );
  await assert.rejects(
    prepareIosFrameworks(ctx, f.project, f.generated),
    /Conflicting/,
  );
});
test("framework ZIP traversal fails without writing outside generated project", async (t) => {
  const f = await frameworkFixture(t, { "../escape": Buffer.from("bad") });
  await assert.rejects(
    prepareIosFrameworks(ctx, f.project, f.generated),
    /Unsafe/,
  );
  await assert.rejects(readFile(path.join(f.generated, "escape")), /ENOENT/);
});
test("framework preparation refuses preexisting links", async (t) => {
  const f = await frameworkFixture(t, {
    "Test.xcframework/Info.plist": Buffer.from("new"),
  });
  await file(path.join(f.root, "outside/Info.plist"), "preserve");
  await mkdir(path.join(f.generated, "Fw"));
  await symlink(
    path.join(f.root, "outside"),
    path.join(f.generated, "Fw/Test.xcframework"),
  );
  await assert.rejects(
    prepareIosFrameworks(ctx, f.project, f.generated),
    /symbolic link/,
  );
  assert.equal(
    await readFile(path.join(f.root, "outside/Info.plist"), "utf8"),
    "preserve",
  );
});
test("runner staged by Xcode must match selected architecture and bytes", async (t) => {
  const root = await temporary(t);
  await file(path.join(root, "project/ios-arm64/libyoyo_yyc.a"), "device");
  await file(
    path.join(root, "project/ios-simulator/libyoyo_yyc_sim.a"),
    "simulator",
  );
  const expected = await runnerHashes(ctx, path.join(root, "project"));
  const staged = path.join(
    root,
    "DerivedData/Build/Products/Release-iphoneos/libyoyo_yyc.a",
  );
  await file(staged, "device");
  await verifyStagedIosRunner(
    ctx,
    path.join(root, "DerivedData"),
    expected,
    false,
  );
  await file(staged, "wrong runtime");
  await assert.rejects(
    verifyStagedIosRunner(ctx, path.join(root, "DerivedData"), expected, false),
    /distribution blocked/,
  );
});
test("iOS configuration exposes native export, simulator and Xcode options", () => {
  assert.equal(
    gms2Schema.safeParse({
      ios: {
        packageType: "ipa",
        exportOptionsPlist: "/private/export.plist",
        teamId: "ABCDEFGHIJ",
        podInstall: true,
      },
    }).success,
    true,
  );
  assert.equal(
    gms2Schema.safeParse({ ios: { packageType: "zip" } }).success,
    false,
  );
});
test("reject non-Mac iOS builds before invoking tools", async () => {
  if (process.platform === "darwin") {
    return;
  }
  await assert.rejects(
    preflightIos(ctx, { type: "package" }, {}),
    /require a Mac/,
  );
});
test("build arguments keep project, license and settings paths as separate argv entries", () => {
  const args = constructIgorBuildArgs(
    ctx,
    {
      igorPath: "/igor",
      licenseFile: "/protected/license with spaces.plist",
      prefabsDir: "/prefabs",
      runtimeDir: "/runtime",
      target: "ios",
      cacheDir: "/cache/invocation-one",
      projectPath: parseProjectPath(ctx, "/project/Game.yyp"),
      projectToolPath: "/project-tool",
      verbose: false,
      runtime: "YYC",
      userDir: "/cache/invocation-one/user",
    },
    "Package",
  );
  assert.equal(
    args[args.indexOf("-lf") + 1],
    "/protected/license with spaces.plist",
  );
  assert.equal(args[args.indexOf("-uf") + 1], "/cache/invocation-one/user");
  assert.deepEqual(args.slice(-3), ["--", "ios", "Package"]);
  assert.equal(args.includes("-jsonErrors"), false);
});

test("archive verification includes Xcode ArchiveIntermediates staging", async (t) => {
  const root = await temporary(t);
  await file(path.join(root, "project/ios-arm64/libyoyo_yyc.a"), "device");
  const expected = await runnerHashes(ctx, path.join(root, "project"));
  await file(
    path.join(
      root,
      "DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/Game/BuildProductsPath/Release-iphoneos/libyoyo_yyc.a",
    ),
    "device",
  );
  await verifyStagedIosRunner(
    ctx,
    path.join(root, "DerivedData"),
    expected,
    false,
  );
});

import {
  parseToolchainVersion,
  toolchainVersionToString,
} from "../src/toolchain";
test("exact custom runtime keeps its suffix through parsing and configuration", () => {
  const selected = parseToolchainVersion("GMS2@2024.14.4.268-c1");
  assert.deepEqual(selected, {
    type: "GMS2",
    version: [2024, 14, 4, 268],
    customVersion: "2024.14.4.268-c1",
  });
  assert.equal(toolchainVersionToString(selected), "GMS2@2024.14.4.268-c1");
  for (const value of [
    "2024.14.4-c1",
    "2024.14.4.268-C1",
    "2024.14.4.268-c0",
    "2024.14.4.268-c01",
    "2024.14.4.268-c1@extra",
  ]) {
    assert.throws(() => parseToolchainVersion("GMS2@" + value));
  }
  assert.equal(
    toolchainVersionToString(parseToolchainVersion("GMS2@2024.14.4.268")),
    "GMS2@2024.14.4.268",
  );
});
